//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telefonszamok_DAL_Konzol
{
    using System;
    using System.Collections.Generic;
    
    public partial class enSzemely
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enSzemely()
        {
            this.enTelefonszamok = new HashSet<enTelefonszam>();
        }
    
        public int Id { get; set; }
        public string Vezeteknev { get; set; }
        public string Utonev { get; set; }
        public string Lakcim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enTelefonszam> enTelefonszamok { get; set; }
        public virtual enHelyseg enHelyseg { get; set; }
    }
}
